### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by yuanchao-sh** [nangongchengfeng/zabbix-api#1]
"io.usedgen[*]",        # 根目录使用率监控 
"disk_capacity.[disk_all_Usage]",#服务器总使用率

--------------------这2个是自定义的监控模板吗？好像默认的模板是自动发现
CPU空闲时间不知道怎么执行脚本一直报错keyerror

**Comment by nangongchengfeng** [comment]
对，这两个属于自定义模板的

**Comment by yuanchao-sh** [comment]
> 对，这两个属于自定义模板的

如果我没有自定义的磁盘监控模板，用它自带的[Template OS Linux by Zabbix agent]模板下面[自动发现清单]/[Mounted filesystem discovery]，不要/目录使用率，将所有的分区目录使用率做个总的磁盘使用率列，要怎么改一下这个GetItems.py啊，分区目录使用率整合那个re.findall(r'^/[a-z0-9]{1,50}: Space utilization', item)怎么把/目录也算进去，py不太熟

**Comment by nangongchengfeng** [comment]
#收集磁盘的总使用率
UserParameter=disk_capacity.[*],/usr/local/zabbix-v503/scripts/disk_capacity.sh $1
UserParameter=io.used[*],count_used=`/usr/bin/df -BM | grep -w "\b$1\b" | awk -F' ' '{ print $$3 }' | awk -F'[ M]+'  '{ print $$1 }'` ;awk 'BEGIN{printf "%.4f\n",('$count_used'/'1000000')}'
UserParameter=io.total[*],count_used=`/usr/bin/df -BM | grep -w "\b$1\b" | awk -F' ' '{ print $$2 }' | awk -F'[ M]+'  '{ print $$1 }'` ;awk 'BEGIN{printf "%.4f\n",('$count_used'/'1000000')}'
#UserParameter=io.total[*],/usr/bin/df -Th | grep -w "\b$1\b" | awk -F' ' '{ print $$3 }'
UserParameter=io.Usagerate[*],/usr/bin/df -Th | grep -w "\b$1\b" | awk -F' ' '{ print $$6 }'| awk -F'[ %]+'  '{ print $$1 }'







scripts/disk_capacity.sh

#!/bin/bash
disk_count(){
    disk=`ls /dev/sd* |awk '{print $NF}'|cut -c 6-8|uniq -c|awk '{print $NF}'`
    count_total=0
    count_used=0

    for d in ${disk}
    do
        total_=`df -BM  | grep $d | awk -F'[ M]+'  '{ print $2 }'`
        used_=`df -BM  | grep $d | awk -F'[ M]+'  '{ print $3 }'`
        for i in  $total_
        do
            let count_total+=$total_
            let count_used+=$used_
        done
    done
    kkk=`awk 'BEGIN{printf "%.4f\n",('$count_used'/'1048576')}'`
    bbb=`awk 'BEGIN{printf "%.4f\n",('$count_total'/'1048576')}'`
    all_total_count=`awk 'BEGIN{printf "%.2f\n",('$kkk'/'$bbb')*100}'`
}
disk_all_Total(){
    disk_count
    echo "${bbb}"
}
disk_all_Used(){
    disk_count
    echo "${kkk}"
}
disk_all_Usage(){
    disk_count
    echo "$all_total_count"
}

$1

**Comment by nangongchengfeng** [comment]
这是这两个自定义的监控项
