### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by peijs** [nangongchengfeng/zabbix-api#2]
(base) root@anonymous:~/Zabbix-api_v1# python main.py 
Traceback (most recent call last):
  File "/root/Zabbix-api_v1/main.py", line 8, in <module>
    from api.zabbixapi.GetItems import Zabbix
ModuleNotFoundError: No module named 'api'

怎么执行脚本报错，，。python，求解

**Comment by nangongchengfeng** [comment]
麻烦修改一下
from GetItems import Zabbix
from SaveToExcel  import WriteExcel
